" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
set nocompatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
" 
" 
" 
"                         YiJun Linux GVim dotfile
"  
"                                2015.1.18 
"
"                 ♥♥♥ I Love You <♥Meredith♥> Forever ♥♥♥
"
"
"
" ========================= Normal Setting Start =========================  
filetype on

" set path


"init
"set windows pos and resize
set lines=50
set columns=90
winpos 200 0
" Rule the define
set ruler
set cursorline
set cc=80
set laststatus=2
" 关闭gui菜单 工具栏
set go=

" Encoding setting
set encoding=utf-8
set fileencodings=utf-8,gb18030,gbk,gb2312,cp936
" 解决提示, 命令行乱码
language messages zh_CN.utf-8
"language messages utf-8

if has('win32')
	set guifont=courier_new:h12
elseif has('unix')
	set guifont=courier\ new\ 15
endif


"color
colorscheme molokai

" ** Make its Gvim Like Windows behave ** 
source $VIMRUNTIME/mswin.vim
behave mswin
" So you can use 
" @ CTRL+S save the file
" @ CTRL+C copy text
" @ CTRL+P paste text
" @ CTRL+X cut text


set regexpengine=1
" Format 
set ts=4
set shiftwidth=4
set softtabstop=4
"行号
set number


" Search and Case
set autoindent
set smartindent
set cindent
set autoread
set ignorecase
" 实时搜索
set incsearch
set hlsearch
" 语法高亮
syntax on 

" No back up files 
set nobackup
set nowritebackup
set noswapfile
" ========================= Normal Setting End =========================  

" ========================= Vim Plugin =================================
" plugin path
if has('unix')
    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc('~/.vim/bundle')
elseif has('win32')
    set rtp+=~/vimfiles/bundle/vundle/
    call vundle#rc('~/vimfiles/bundle')
endif

" Bundle plugin
Bundle 'L9'
Bundle 'FuzzyFinder'
Bundle 'The-NERD-tree'
"Bundle 'vim-airline'
Bundle 'kien/ctrlp.vim'
if has('win32')
    "set runtimepath+=~/vimfiles/bundle/ycm-windows-x86
elseif
    Bundle 'Valloric/YouCompleteMe'
endif


" ========================= Vim Plugin End ===============================

" ========================= Keymap =======================================
nnoremap <C-o> :FufFile<CR>

